# Generated by Django 3.1.5 on 2021-01-11 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_pontaj'),
        ('userprofile', '0003_auto_20210106_1812'),
    ]

    operations = [
    ]
